Generator for Honeybadger and Sentry
TruemarkDev/boring_generators pull request #10
Opened 2024-04-14 15:52 UTC by mausamp

2024-04-15 04:05 UTC, TheZero0-ctrl commented on lib/generators/boring/honeybadger/install/install_generator.rb
> +          if options[:api_key].blank?
Instead of doing this make this option required

2024-04-17 07:14 UTC, coolprobn requested changes

2024-04-17 07:14 UTC, coolprobn commented on lib/generators/boring/sentry/install/install_generator.rb
> +            config.dsn = Rails.application.credentials.dig(:sentry, :dsn_key)
We need to provide an option to user so they can provide us with the key to look for and also a way to use ENV instead of Rails credentials, you can check the PR for devise-jwt to see how Ankit has done it.

2024-04-17 07:14 UTC, coolprobn commented on lib/generators/boring/sentry/install/install_generator.rb
> +            config.breadcrumbs_logger = [:active_support_logger, :http_logger]
This should also be taken from user while these can be defaults

2024-04-17 07:14 UTC, coolprobn commented on lib/generators/boring/sentry/install/install_generator.rb
> +        say 'Please add your dsn key to your rails credentials under sentry.dsn_key', :yellow
Let's notify about these things separately at the end of the generator (by creating new method) so they are not missed by the user.

2024-04-17 07:14 UTC, coolprobn commented on lib/generators/boring/sentry/install/install_generator.rb
> +        say 'Please add your dsn key to your rails credentials under sentry.dsn_key', :yellow
Also message could be a bit better, you can take a look at this example from another generator:

```
say "❗️❗️\nusername will be used from `ENV.fetch('SWAGGER_UI_LOGIN_USERNAME', 'admin')` and password from `Rails.application.credentials.dig(:swagger_ui, :password)`. You can change these values if they don't match with your app.\n", :yellow
```

2024-05-06 05:56 UTC, coolprobn requested changes

2024-05-06 05:56 UTC, coolprobn commented on lib/generators/boring/sentry/install/install_generator.rb
> +                   desc: 'Use ENV variable for devise_jwt_secret_key. By default Rails credentials will be used.'
Need to remove devise_jwt_secret_key ....

2024-05-06 05:56 UTC, coolprobn commented on lib/generators/boring/sentry/install/install_generator.rb
> +        create_file 'config/initializers/sentry.rb', sentry_config
Let's use template to do this since we are creating new file, you have already done similar thing in brakeman with github ci

2024-05-06 05:56 UTC, coolprobn commented on lib/generators/boring/sentry/install/install_generator.rb
> +        if options[:use_env_variable]
Let's update to

```
dsn_key_location = if options[:use_env_variable]
  ENV['SENTRY_DSN_KEY']
else
  Rails.application.credentials.dig(:sentry, :dsn_key)
end

say "❗️❗️\nThe DSN key for Sentry will be used from `#{dsn_key_location}`. You can change this value if it doesn't match with your app.\n", :yellow
```

2024-05-06 05:56 UTC, coolprobn commented on lib/generators/boring/sentry/install/install_generator.rb
> +
Let's add "default: " with default values as well

you can see https://github.com/TruemarkDev/boring_generators/blob/e034ce5e124a076c2f036a8f881696b8279aa1e4/lib/generators/boring/rswag/install/install_generator.rb on how we are using default values with class_option

2024-05-06 05:56 UTC, coolprobn commented on lib/generators/boring/sentry/install/install_generator.rb
> +          [:active_support_logger, :http_logger]
This should come from default value for the class_option

2024-05-06 05:56 UTC, coolprobn commented on test/generators/sentry_install_generator_test.rb
> +  def test_should_configure_sentry_gem_with_env_variable
Let's update to "test_should_configure_dsn_key_as_env_variable"

2024-05-06 05:56 UTC, coolprobn commented on test/generators/sentry_install_generator_test.rb
> +  def test_should_configure_sentry_gem_with_custom_breadcrumbs_logger
Let's update to "test_should_configure_custom_breadcrumbs_logger"

2024-05-07 14:38 UTC, coolprobn approved these changes

2024-05-31 07:18 UTC, merged