generator for dotenv
TruemarkDev/boring_generators pull request #14
Opened 2024-04-17 15:29 UTC by mausamp

2024-04-22 14:16 UTC, TheZero0-ctrl commented on test/generators/dotenv_install_generator_test.rb
> +  def test_should_install_dotenv_successfully
let's remove successfully

2024-05-06 06:02 UTC, coolprobn requested changes

2024-05-06 06:02 UTC, coolprobn commented on lib/generators/boring/dotenv/install/install_generator.rb
> +        end
Let's also create .env.sample by copying the .env file

2024-05-07 14:28 UTC, coolprobn approved these changes

2024-05-31 07:43 UTC, merged